export type Category = "movement" | "editing" | "mode" | "search";
export type Difficulty = "beginner" | "intermediate" | "advanced";
export type Language = "javascript" | "python" | "html" | "css" | "cpp";

export interface Challenge {
  id: string;
  title: string;
  description: string;
  category: Category;
  difficulty: Difficulty;
  language?: Language;
  initialContent: string;
  targetContent: string;
  hint: string;
  solution: string;
  points: number;
  parTime: number;
}

// ─── 初級 ────────────────────────────────────────────────────────────────────

const BEGINNER: Challenge[] = [
  // Movement
  {
    id: "hjkl-basic",
    title: "hjkl 移動 + 編集",
    description: "3行目の 'spot' を 'place' に変更せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "Hello World\nVim is powerful\nX marks the spot",
    targetContent: "Hello World\nVim is powerful\nX marks the place",
    hint: "j で下へ、w で単語移動、cw で単語変更",
    solution: "jj$b cw place<Esc>",
    points: 150,
    parTime: 40,
  },
  {
    id: "word-movement",
    title: "単語ジャンプ + 挿入",
    description: "'powerful' の前に 'very ' を挿入せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "Vim is powerful and fast",
    targetContent: "Vim is very powerful and fast",
    hint: "w で次の単語の先頭へ、i で挿入モード",
    solution: "ww i very <Space><Esc>",
    points: 200,
    parTime: 30,
  },
  {
    id: "line-movement",
    title: "行末移動 + 追記",
    description: "行末に '!' を追加せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "Vim is awesome",
    targetContent: "Vim is awesome!",
    hint: "A で行末に挿入モード、または $ → a",
    solution: "A!<Esc>",
    points: 100,
    parTime: 20,
  },
  {
    id: "goto-last-line",
    title: "最終行へジャンプ (G)",
    description: "最終行の 'old' を 'new' に変更せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "Line 1\nLine 2\nLine 3\nold content",
    targetContent: "Line 1\nLine 2\nLine 3\nnew content",
    hint: "G で最終行へジャンプ、cw で単語変更",
    solution: "G cw new<Esc>",
    points: 150,
    parTime: 20,
  },
  {
    id: "goto-first-line",
    title: "G でヤンク → gg で先頭に戻って貼り付け",
    description: "末尾行の 'Vim' をヤンクし、gg で先頭に戻って 'BLANK' を置き換えよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "Hello BLANK world\nLine 2\nLine 3\nVim",
    targetContent: "Hello Vim world\nLine 2\nLine 3\nVim",
    hint: "G → yw でヤンク → gg → fB → viwp で置き換え",
    solution: "G yw  gg fB viwp",
    points: 250,
    parTime: 30,
  },
  {
    id: "find-char",
    title: "行内文字検索 (f)",
    description: "f で 'f' にジャンプして 'fox' を 'cat' に変更せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "The quick brown fox jumps",
    targetContent: "The quick brown cat jumps",
    hint: "ff で行内の 'f' へジャンプ、cw で変更",
    solution: "ff cw cat<Esc>",
    points: 150,
    parTime: 20,
  },
  {
    id: "goto-line-number",
    title: "行番号ジャンプ (nG)",
    description: "5行目の 'target' を 'goal' に変更せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "Line 1\nLine 2\nLine 3\nLine 4\ntarget line\nLine 6\nLine 7",
    targetContent: "Line 1\nLine 2\nLine 3\nLine 4\ngoal line\nLine 6\nLine 7",
    hint: "5G で5行目へ直接ジャンプ、cw で変更",
    solution: "5G cw goal<Esc>",
    points: 200,
    parTime: 20,
  },
  {
    id: "first-nonblank",
    title: "行頭の非空白文字へ (^)",
    description: "インデントされた行の先頭の 'item' を 'task' に変更せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "  item one\n  item two",
    targetContent: "  task one\n  item two",
    hint: "^ で最初の非空白文字へジャンプ、cw で変更",
    solution: "^ cw task<Esc>",
    points: 150,
    parTime: 15,
  },
  {
    id: "match-paren",
    title: "対応する括弧へジャンプ (%)",
    description: "'(' から % で ')' にジャンプして行末に ';' を追加せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "result = (a + b)",
    targetContent: "result = (a + b);",
    hint: "f( で '(' へ移動、% で対応する ')' にジャンプ、a で追記",
    solution: "f( % a;<Esc>",
    points: 200,
    parTime: 20,
  },
  {
    id: "count-motion",
    title: "カウント付き移動 (3j)",
    description: "3j で4行目に移動し、'update' を 'done' に変更せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "Line 1\nLine 2\nLine 3\nLine 4 update me\nLine 5",
    targetContent: "Line 1\nLine 2\nLine 3\nLine 4 done me\nLine 5",
    hint: "3j で3行下へ移動（4行目）、fu で 'update' にジャンプ、cw で変更",
    solution: "3j fu cw done<Esc>",
    points: 200,
    parTime: 25,
  },
  {
    id: "till-char-delete",
    title: "文字の手前まで削除 (dt)",
    description: "':remove_this' を削除して 'key=value' にせよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "key:remove_this=value",
    targetContent: "key=value",
    hint: "f: で ':' にジャンプ、dt= で '=' の手前まで削除",
    solution: "f: dt=",
    points: 200,
    parTime: 20,
  },
  {
    id: "prev-word-end",
    title: "前の単語末尾へ (ge)",
    description: "ge で 'Hello' の末尾に戻って '!' を追加せよ",
    category: "movement",
    difficulty: "beginner",
    initialContent: "Hello World",
    targetContent: "Hello! World",
    hint: "W で 'World' へ移動、ge で前の単語末尾 ('Hello' の 'o') へ、a で追記",
    solution: "W ge a!<Esc>",
    points: 200,
    parTime: 20,
  },
  // Editing
  {
    id: "delete-word",
    title: "単語削除 (dw)",
    description: "'useless' という単語を削除せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "This is useless text here",
    targetContent: "This is text here",
    hint: "fu で 'useless' にジャンプ、dw で単語削除",
    solution: "fu dw",
    points: 200,
    parTime: 25,
  },
  {
    id: "delete-line",
    title: "行削除 (dd)",
    description: "2行目を削除せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Keep this line\nDelete this line\nKeep this too",
    targetContent: "Keep this line\nKeep this too",
    hint: "j で2行目へ、dd で行削除",
    solution: "j dd",
    points: 150,
    parTime: 20,
  },
  {
    id: "yank-paste",
    title: "コピー＆ペースト (yy / p)",
    description: "1行目をコピーして3行目の後ろにペーストせよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Copy me\nSecond line\nThird line",
    targetContent: "Copy me\nSecond line\nThird line\nCopy me",
    hint: "yy でヤンク、jj で移動、p でペースト",
    solution: "yy G p",
    points: 250,
    parTime: 30,
  },
  {
    id: "change-word",
    title: "単語変更 (cw)",
    description: "'bad' を 'good' に変更せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "This is a bad example",
    targetContent: "This is a good example",
    hint: "fb で 'bad' にジャンプ、cw で変更",
    solution: "fb cw good<Esc>",
    points: 200,
    parTime: 25,
  },
  {
    id: "delete-to-end",
    title: "行末まで削除 (D)",
    description: "'delete' の位置から行末まで削除せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Keep this delete from here",
    targetContent: "Keep this ",
    hint: "fd で 'delete' にジャンプ、D で行末まで削除",
    solution: "fd D",
    points: 200,
    parTime: 20,
  },
  {
    id: "delete-char",
    title: "1文字削除 (x)",
    description: "'Helllo' の余分な 'l' を1つ削除せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Helllo World",
    targetContent: "Hello World",
    hint: "fl で余分な 'l' にジャンプ、x で1文字削除",
    solution: "fl ; x",
    points: 100,
    parTime: 15,
  },
  {
    id: "replace-char",
    title: "1文字置換 (r)",
    description: "'Hxllo' の 'x' を 'e' に置換せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Hxllo World",
    targetContent: "Hello World",
    hint: "fx で 'x' にジャンプ、re で1文字置換",
    solution: "fx re",
    points: 100,
    parTime: 15,
  },
  {
    id: "join-lines",
    title: "行の結合 (J)",
    description: "2行を1行に結合せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Hello\nWorld",
    targetContent: "Hello World",
    hint: "J で現在行と次行を結合",
    solution: "J",
    points: 150,
    parTime: 10,
  },
  {
    id: "change-to-eol",
    title: "行末まで変更 (C)",
    description: "'wrong' の位置から行末を 'correct' に変更せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "This is wrong content here",
    targetContent: "This is correct",
    hint: "fw で 'wrong' にジャンプ、C で行末まで変更して入力",
    solution: "fw C correct<Esc>",
    points: 200,
    parTime: 20,
  },
  {
    id: "move-line",
    title: "行の移動 (dd + P)",
    description: "2行目の 'First' を1行目に移動せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Second\nFirst\nThird",
    targetContent: "First\nSecond\nThird",
    hint: "j → dd でカット、k → P（大文字）で前の行にペースト",
    solution: "j dd k P",
    points: 300,
    parTime: 25,
  },
  {
    id: "delete-to-char",
    title: "指定文字まで削除 (df)",
    description: "コロンを含めて前の部分を削除し 'keep_this' だけ残せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "delete_this:keep_this",
    targetContent: "keep_this",
    hint: "df: でコロンを含めて削除",
    solution: "df:",
    points: 200,
    parTime: 15,
  },
  {
    id: "delete-multiple-words",
    title: "複数単語削除 (d3w)",
    description: "'remove those words' の3単語をまとめて削除せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Keep these remove those words here",
    targetContent: "Keep these here",
    hint: "fr で 'remove' にジャンプ、d3w で3単語まとめて削除",
    solution: "fr d3w",
    points: 250,
    parTime: 20,
  },
  {
    id: "replace-mode",
    title: "Replace モード (R)",
    description: "Replace モードで 'wrong' を 'right' に書き換えよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "This is wrong text",
    targetContent: "This is right text",
    hint: "fw で移動、R で Replace モード開始、right と入力して ESC",
    solution: "fw R right<Esc>",
    points: 200,
    parTime: 20,
  },
  {
    id: "change-line",
    title: "行全体を変更 (cc)",
    description: "2行目をまるごと 'New content' に書き換えよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "First line\nOld content here\nThird line",
    targetContent: "First line\nNew content\nThird line",
    hint: "j で2行目へ、cc で行全体を削除して挿入モード、入力して ESC",
    solution: "j cc New content<Esc>",
    points: 200,
    parTime: 20,
  },
  {
    id: "substitute-char",
    title: "1文字削除して挿入 (s)",
    description: "'[X] Done' の 'X' を 'v' に置き換えよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "[X] Done",
    targetContent: "[v] Done",
    hint: "fX で 'X' にジャンプ、s で削除して挿入モード、v を入力",
    solution: "fX sv<Esc>",
    points: 100,
    parTime: 15,
  },
  {
    id: "repeat-command",
    title: "直前のコマンドを繰り返す (.)",
    description: "'bad1' 'bad2' 'bad3' をすべて 'good' に変更せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "bad1 bad2 bad3",
    targetContent: "good good good",
    hint: "fb → cw good<Esc> で最初を変更、W → . で残りを繰り返す",
    solution: "fb cw good<Esc> W . W .",
    points: 300,
    parTime: 30,
  },
  {
    id: "delete-around-word",
    title: "単語と空白を削除 (daw)",
    description: "'extra' という単語をスペースごと削除せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "keep extra here",
    targetContent: "keep here",
    hint: "fe で 'extra' にジャンプ、daw で単語と周囲のスペースを削除",
    solution: "fe daw",
    points: 200,
    parTime: 15,
  },
  {
    id: "change-inner-word",
    title: "単語全体を変更 (ciw)",
    description: "カーソルが単語内のどこにあっても ciw で 'hello' を 'world' に変更せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "say hello there",
    targetContent: "say world there",
    hint: "fh で 'hello' にジャンプ、ciw で単語全体を変更",
    solution: "fh ciw world<Esc>",
    points: 200,
    parTime: 20,
  },
  {
    id: "change-inside-quotes",
    title: "引用符内を変更 (ci\")",
    description: "引用符内の文字列を 'new_value' に書き換えよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "const x = \"old_value\";",
    targetContent: "const x = \"new_value\";",
    hint: "f\" で引用符へ移動、ci\" で内側を変更",
    solution: "f\" ci\" new_value<Esc>",
    points: 250,
    parTime: 20,
  },
  {
    id: "delete-inside-quotes",
    title: "引用符内を削除 (di\")",
    description: "引用符内の文字列を削除して空の引用符にせよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "name = \"remove this content\"",
    targetContent: "name = \"\"",
    hint: "f\" で引用符へ移動、di\" で内側を削除",
    solution: "f\" di\"",
    points: 200,
    parTime: 15,
  },
  {
    id: "toggle-case",
    title: "大文字小文字を反転 (~)",
    description: "'hello WORLD' を 'HELLO world' に変換せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "hello WORLD",
    targetContent: "HELLO world",
    hint: "5~ で最初の5文字を反転、W で次の単語へ、5~ で反転",
    solution: "5~ W 5~",
    points: 300,
    parTime: 25,
  },
  {
    id: "delete-to-eof",
    title: "カーソルから末尾まで削除 (dG)",
    description: "2行目から末尾まですべて削除せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Keep this line\nDelete from here\nAnd this\nAnd this too",
    targetContent: "Keep this line",
    hint: "j で2行目へ、dG でカーソル行から末尾まで削除",
    solution: "j dG",
    points: 250,
    parTime: 15,
  },
  {
    id: "count-delete-lines",
    title: "複数行を一度に削除 (2dd)",
    description: "2行目と3行目を一度のコマンドで削除せよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Line 1\nLine 2\nLine 3\nLine 4",
    targetContent: "Line 1\nLine 4",
    hint: "j で2行目へ、2dd で2行まとめて削除",
    solution: "j 2dd",
    points: 200,
    parTime: 15,
  },
  {
    id: "yank-multiple-lines",
    title: "複数行ヤンクしてペースト (3yy)",
    description: "最初の3行をヤンクして末尾にペーストせよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Alpha\nBeta\nGamma\n---",
    targetContent: "Alpha\nBeta\nGamma\n---\nAlpha\nBeta\nGamma",
    hint: "3yy で3行ヤンク、G で末尾へ、p でペースト",
    solution: "3yy G p",
    points: 300,
    parTime: 30,
  },
  {
    id: "delete-all-content",
    title: "全内容を削除 (gg + dG)",
    description: "ファイルの内容をすべて削除して空にせよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Line 1\nLine 2\nLine 3\nLine 4\nLine 5",
    targetContent: "",
    hint: "gg でファイル先頭へ、dG でカーソル行から末尾まで削除",
    solution: "gg dG",
    points: 200,
    parTime: 15,
  },
  {
    id: "yank-all-paste",
    title: "全内容をヤンクして末尾に貼り付け (yG)",
    description: "ファイルの全内容をヤンクして末尾に貼り付けよ",
    category: "editing",
    difficulty: "beginner",
    initialContent: "Line 1\nLine 2\nLine 3",
    targetContent: "Line 1\nLine 2\nLine 3\nLine 1\nLine 2\nLine 3",
    hint: "gg でファイル先頭へ、yG で末尾までヤンク、G で最終行へ、p でペースト",
    solution: "gg yG G p",
    points: 300,
    parTime: 25,
  },
  // Mode
  {
    id: "insert-mode",
    title: "Insert モードで追記 (A)",
    description: "テキストの末尾に ' rocks!' を追加せよ",
    category: "mode",
    difficulty: "beginner",
    initialContent: "Vim",
    targetContent: "Vim rocks!",
    hint: "A で行末に挿入モード、ESC で Normal モードに戻る",
    solution: "A rocks!<Esc>",
    points: 150,
    parTime: 20,
  },
  {
    id: "insert-new-line",
    title: "下に新しい行を挿入 (o)",
    description: "1行目の下に 'Hello Vim!' を追加せよ",
    category: "mode",
    difficulty: "beginner",
    initialContent: "Line 1\nLine 3",
    targetContent: "Line 1\nHello Vim!\nLine 3",
    hint: "o で下に新しい行を挿入",
    solution: "o Hello Vim!<Esc>",
    points: 150,
    parTime: 25,
  },
  {
    id: "insert-above",
    title: "上に新しい行を挿入 (O)",
    description: "1行目の上に 'Header' を追加せよ",
    category: "mode",
    difficulty: "beginner",
    initialContent: "First line\nSecond line",
    targetContent: "Header\nFirst line\nSecond line",
    hint: "O（大文字）で上に新しい行を挿入",
    solution: "O Header<Esc>",
    points: 150,
    parTime: 20,
  },
  {
    id: "insert-beginning",
    title: "行頭に挿入 (I)",
    description: "行頭に 'Hello ' を追加せよ",
    category: "mode",
    difficulty: "beginner",
    initialContent: "world",
    targetContent: "Hello world",
    hint: "I（大文字）で行頭に挿入モード",
    solution: "I Hello <Esc>",
    points: 100,
    parTime: 15,
  },
  {
    id: "append-word-end",
    title: "単語末尾に追記 (ea)",
    description: "'Vim' の後ろに '!' を追加せよ",
    category: "mode",
    difficulty: "beginner",
    initialContent: "I love Vim",
    targetContent: "I love Vim!",
    hint: "fV で 'Vim' へジャンプ、ea で単語末尾に追記",
    solution: "fV ea!<Esc>",
    points: 150,
    parTime: 15,
  },
  {
    id: "visual-select-delete",
    title: "Visual で選択して削除 (v + d)",
    description: "v で 'XXX ' を選択して削除し、'Hello World' にせよ",
    category: "mode",
    difficulty: "beginner",
    initialContent: "Hello XXX World",
    targetContent: "Hello World",
    hint: "fX で 'X' へ、v でビジュアルモード、3l で4文字選択、d で削除",
    solution: "fX v 3l d",
    points: 250,
    parTime: 20,
  },
  {
    id: "visual-line-delete",
    title: "行選択モードで複数行削除 (V + d)",
    description: "V で2〜3行目を選択して削除せよ",
    category: "mode",
    difficulty: "beginner",
    initialContent: "Keep\nDelete me\nDelete me too\nKeep",
    targetContent: "Keep\nKeep",
    hint: "j で2行目へ、V で行選択モード、j で3行目まで拡張、d で削除",
    solution: "j V j d",
    points: 250,
    parTime: 20,
  },
  {
    id: "visual-line-yank-paste",
    title: "行選択でヤンクしてペースト (V + y + p)",
    description: "1行目を V でヤンクして3行目の下に貼り付けよ",
    category: "mode",
    difficulty: "beginner",
    initialContent: "Line A\nLine B\nLine C",
    targetContent: "Line A\nLine B\nLine C\nLine A",
    hint: "V で行選択、y でヤンク、G で末尾へ、p でペースト",
    solution: "V y G p",
    points: 250,
    parTime: 25,
  },
  // Search
  {
    id: "search-basic",
    title: "検索してジャンプ + 編集",
    description: "/target で最初の 'target' を検索し、'found' に変更せよ",
    category: "search",
    difficulty: "beginner",
    initialContent: "Find the target word\nin this text\nthe target is here",
    targetContent: "Find the found word\nin this text\nthe target is here",
    hint: "/target で検索、Enter 後に cw で単語変更",
    solution: "/target<CR> cw found<Esc>",
    points: 200,
    parTime: 30,
  },
  {
    id: "search-replace",
    title: "全置換 (:%s)",
    description: "すべての 'foo' を 'bar' に置換せよ",
    category: "search",
    difficulty: "beginner",
    initialContent: "foo is here\nAnother foo\nLast foo",
    targetContent: "bar is here\nAnother bar\nLast bar",
    hint: ":%s/foo/bar/g で全置換",
    solution: ":%s/foo/bar/g<CR>",
    points: 350,
    parTime: 25,
  },
  {
    id: "search-next",
    title: "検索 + n で次の一致へ",
    description: "/error で検索し、n で移動して最後の 'error' を 'fixed' に変更せよ",
    category: "search",
    difficulty: "beginner",
    initialContent: "error found here\nAnother error line\nlast error end",
    targetContent: "error found here\nAnother error line\nlast fixed end",
    hint: "/error → Enter → n → n で最後へ、cw で変更",
    solution: "/error<CR> n n cw fixed<Esc>",
    points: 250,
    parTime: 30,
  },
  {
    id: "search-under-cursor",
    title: "カーソル下の単語を検索 (*)",
    description: "* で 'error' を検索し、2番目の 'error' を 'bug' に変更せよ",
    category: "search",
    difficulty: "beginner",
    initialContent: "error in line one\nsecond error here\nno match here",
    targetContent: "error in line one\nsecond bug here\nno match here",
    hint: "* は次のマッチへジャンプする。カーソルが1番目の 'error' の上なら * で2番目へ飛ぶ、cw で変更",
    solution: "* cw bug<Esc>",
    points: 250,
    parTime: 25,
  },
  {
    id: "global-delete",
    title: "パターン行削除 (:g)",
    description: "'#' で始まるコメント行をすべて削除せよ",
    category: "search",
    difficulty: "beginner",
    initialContent: "keep this\n# comment line\nkeep this too\n# another comment\nfinal line",
    targetContent: "keep this\nkeep this too\nfinal line",
    hint: ":g/^#/d で # で始まる行をすべて削除",
    solution: ":g/^#/d<CR>",
    points: 400,
    parTime: 20,
  },
  {
    id: "search-case-insensitive",
    title: "大文字小文字を無視して置換",
    description: "'Hello' と 'hello' をすべて 'hi' に置換せよ",
    category: "search",
    difficulty: "beginner",
    initialContent: "Hello world\nhello there\nHello again",
    targetContent: "hi world\nhi there\nhi again",
    hint: ":%s/hello/hi/gi でフラグ i を付けて大文字小文字無視",
    solution: ":%s/hello/hi/gi<CR>",
    points: 350,
    parTime: 25,
  },
  {
    id: "search-backward",
    title: "後方検索 (?)",
    description: "ファイル末尾から ?first で後方検索し、'first' を 'last' に変更せよ",
    category: "search",
    difficulty: "beginner",
    initialContent: "first item\nsecond item\nthird item",
    targetContent: "last item\nsecond item\nthird item",
    hint: "G で末尾へ、?first<CR> で後方検索、cw で変更",
    solution: "G ?first<CR> cw last<Esc>",
    points: 250,
    parTime: 25,
  },
  {
    id: "line-substitute",
    title: "現在行のみ置換 (:s)",
    description: "2行目の 'cat' だけを 'dog' に置換せよ（他の行は変えない）",
    category: "search",
    difficulty: "beginner",
    initialContent: "I have a cat\nMy cat is big\nCat lover",
    targetContent: "I have a cat\nMy dog is big\nCat lover",
    hint: "j で2行目へ、:s/cat/dog/ で現在行のみ置換",
    solution: "j :s/cat/dog/<CR>",
    points: 250,
    parTime: 20,
  },
];

// ─── 中級 ────────────────────────────────────────────────────────────────────

const INTERMEDIATE: Challenge[] = [
  {
    id: "mid-rename-function",
    language: "javascript" as Language,
    title: "関数名をリネーム",
    description: "コード内の 'fetchUser' をすべて 'getUser' にリネームせよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "function fetchUser(id) {",
      "  return api.get('/users/' + id);",
      "}",
      "",
      "async function loadDashboard(userId) {",
      "  const user = await fetchUser(userId);",
      "  const posts = await fetchPosts(user.id);",
      "  return { user, posts };",
      "}",
      "",
      "router.get('/me', async (req, res) => {",
      "  const user = await fetchUser(req.session.userId);",
      "  res.json(user);",
      "});",
    ].join("\n"),
    targetContent: [
      "function getUser(id) {",
      "  return api.get('/users/' + id);",
      "}",
      "",
      "async function loadDashboard(userId) {",
      "  const user = await getUser(userId);",
      "  const posts = await fetchPosts(user.id);",
      "  return { user, posts };",
      "}",
      "",
      "router.get('/me', async (req, res) => {",
      "  const user = await getUser(req.session.userId);",
      "  res.json(user);",
      "});",
    ].join("\n"),
    hint: ":%s/fetchUser/getUser/g",
    solution: ":%s/fetchUser/getUser/g<CR>",
    points: 300,
    parTime: 20,
  },
  {
    id: "mid-var-const",
    language: "javascript" as Language,
    title: "var を const に一括変換",
    description: "すべての var を const に変換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "var express = require('express');",
      "var router = express.Router();",
      "var db = require('./database');",
      "var jwt = require('jsonwebtoken');",
      "",
      "var SECRET_KEY = process.env.JWT_SECRET;",
      "var TOKEN_EXPIRY = '24h';",
    ].join("\n"),
    targetContent: [
      "const express = require('express');",
      "const router = express.Router();",
      "const db = require('./database');",
      "const jwt = require('jsonwebtoken');",
      "",
      "const SECRET_KEY = process.env.JWT_SECRET;",
      "const TOKEN_EXPIRY = '24h';",
    ].join("\n"),
    hint: ":%s/^var /const /g で行頭の var だけ置換",
    solution: ":%s/^var /const /g<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-delete-logs",
    language: "javascript" as Language,
    title: "console.log を一括削除",
    description: "デバッグ用の console.log をすべて削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "async function processPayment(order) {",
      "  console.log('Processing payment:', order.id);",
      "  const charge = await stripe.charges.create({",
      "    amount: order.total,",
      "    currency: 'jpy',",
      "    source: order.token,",
      "  });",
      "  console.log('Charge created:', charge.id);",
      "  await db.orders.update(order.id, { chargeId: charge.id });",
      "  console.log('Order updated successfully');",
      "  return charge;",
      "}",
    ].join("\n"),
    targetContent: [
      "async function processPayment(order) {",
      "  const charge = await stripe.charges.create({",
      "    amount: order.total,",
      "    currency: 'jpy',",
      "    source: order.token,",
      "  });",
      "  await db.orders.update(order.id, { chargeId: charge.id });",
      "  return charge;",
      "}",
    ].join("\n"),
    hint: ":g/console.log/d でマッチした行をすべて削除",
    solution: ":g/console.log/d<CR>",
    points: 350,
    parTime: 20,
  },
  {
    id: "mid-delete-comments",
    language: "python" as Language,
    title: "コメントアウトされたコードを削除",
    description: "コメントアウトされた古いコードをすべて削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "def authenticate(username, password):",
      "    # Legacy authentication code",
      "    # if username in HARDCODED_USERS:",
      "    #     return HARDCODED_USERS[username] == password",
      "    # return False",
      "    user = User.query.filter_by(username=username).first()",
      "    if not user:",
      "        return False",
      "    return user.check_password(password)",
    ].join("\n"),
    targetContent: [
      "def authenticate(username, password):",
      "    user = User.query.filter_by(username=username).first()",
      "    if not user:",
      "        return False",
      "    return user.check_password(password)",
    ].join("\n"),
    hint: ":g/    #/d でインデントつきコメント行を削除",
    solution: ":g/    #/d<CR>",
    points: 350,
    parTime: 25,
  },
  {
    id: "mid-add-property",
    language: "javascript" as Language,
    title: "オブジェクトにプロパティを追加",
    description: "port の行末にカンマを追加し、次の行に timeout: 5000 を追加せよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: [
      "const serverConfig = {",
      "  host: '0.0.0.0',",
      "  port: 3000",
      "};",
    ].join("\n"),
    targetContent: [
      "const serverConfig = {",
      "  host: '0.0.0.0',",
      "  port: 3000,",
      "  timeout: 5000",
      "};",
    ].join("\n"),
    hint: "/port で移動、A で末尾に , を追記、o で新行に timeout: 5000 を入力",
    solution: "/port<CR> A,<Esc> o  timeout: 5000<Esc>",
    points: 400,
    parTime: 40,
  },
  {
    id: "mid-optional-chain",
    language: "javascript" as Language,
    title: "オプショナルチェーンの追加",
    description: "すべての user.x を user?.x に変換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "function renderProfile(user) {",
      "  const name = user.name;",
      "  const email = user.email;",
      "  const bio = user.bio;",
      "  const avatar = user.avatar;",
      "  return { name, email, bio, avatar };",
      "}",
    ].join("\n"),
    targetContent: [
      "function renderProfile(user) {",
      "  const name = user?.name;",
      "  const email = user?.email;",
      "  const bio = user?.bio;",
      "  const avatar = user?.avatar;",
      "  return { name, email, bio, avatar };",
      "}",
    ].join("\n"),
    hint: ":%s/user\\./user?./g で user. をすべて user?. に一括置換",
    solution: ":%s/user\\./user?./g<CR>",
    points: 400,
    parTime: 30,
  },
  {
    id: "mid-html-tags",
    language: "html" as Language,
    title: "HTML タグを一括置換",
    description: "div タグをすべて section に変更せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "<div class=\"wrapper\">",
      "  <div class=\"header\">",
      "    <h1>My App</h1>",
      "    <nav>Navigation</nav>",
      "  </div>",
      "  <div class=\"main\">",
      "    <p>Main content here</p>",
      "  </div>",
      "  <div class=\"footer\">",
      "    <p>Footer text</p>",
      "  </div>",
      "</div>",
    ].join("\n"),
    targetContent: [
      "<section class=\"wrapper\">",
      "  <section class=\"header\">",
      "    <h1>My App</h1>",
      "    <nav>Navigation</nav>",
      "  </section>",
      "  <section class=\"main\">",
      "    <p>Main content here</p>",
      "  </section>",
      "  <section class=\"footer\">",
      "    <p>Footer text</p>",
      "  </section>",
      "</section>",
    ].join("\n"),
    hint: ":%s/div/section/g で開閉タグを含めて一括置換",
    solution: ":%s/div/section/g<CR>",
    points: 300,
    parTime: 20,
  },

  // ── C++ ──────────────────────────────────────────────────────────────────
  {
    id: "mid-cpp-delete-cerr",
    language: "cpp" as Language,
    title: "デバッグ出力を削除",
    description: "デバッグ用の cerr 出力行をすべて削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "int solve(int n) {",
      "    cerr << \"Input: \" << n << endl;",
      "    int ans = 0;",
      "    for (int i = 1; i <= n; i++) {",
      "        ans += i;",
      "        cerr << \"Step: \" << ans << endl;",
      "    }",
      "    cerr << \"Answer: \" << ans << endl;",
      "    return ans;",
      "}",
    ].join("\n"),
    targetContent: [
      "int solve(int n) {",
      "    int ans = 0;",
      "    for (int i = 1; i <= n; i++) {",
      "        ans += i;",
      "    }",
      "    return ans;",
      "}",
    ].join("\n"),
    hint: ":g/cerr/d でマッチした行をすべて削除",
    solution: ":g/cerr/d<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-cpp-rename-func",
    language: "cpp" as Language,
    title: "関数名を一括リネーム",
    description: "'computeSum' を 'sum' に、'computeProduct' を 'product' にリネームせよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "int computeSum(int a, int b) {",
      "    return a + b;",
      "}",
      "",
      "int computeProduct(int a, int b) {",
      "    return a * b;",
      "}",
      "",
      "int main() {",
      "    cout << computeSum(3, 4) << endl;",
      "    cout << computeProduct(3, 4) << endl;",
      "    return 0;",
      "}",
    ].join("\n"),
    targetContent: [
      "int sum(int a, int b) {",
      "    return a + b;",
      "}",
      "",
      "int product(int a, int b) {",
      "    return a * b;",
      "}",
      "",
      "int main() {",
      "    cout << sum(3, 4) << endl;",
      "    cout << product(3, 4) << endl;",
      "    return 0;",
      "}",
    ].join("\n"),
    hint: ":%s/computeSum/sum/g → :%s/computeProduct/product/g で2回置換",
    solution: ":%s/computeSum/sum/g<CR>\n:%s/computeProduct/product/g<CR>",
    points: 350,
    parTime: 25,
  },
  {
    id: "mid-cpp-null-to-nullptr",
    language: "cpp" as Language,
    title: "NULL を nullptr に変換",
    description: "古い NULL をすべて nullptr に変換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "int* ptr = NULL;",
      "Node* head = NULL;",
      "Node* tail = NULL;",
      "",
      "if (ptr == NULL) {",
      "    head = NULL;",
      "}",
    ].join("\n"),
    targetContent: [
      "int* ptr = nullptr;",
      "Node* head = nullptr;",
      "Node* tail = nullptr;",
      "",
      "if (ptr == nullptr) {",
      "    head = nullptr;",
      "}",
    ].join("\n"),
    hint: ":%s/NULL/nullptr/g で全置換",
    solution: ":%s/NULL/nullptr/g<CR>",
    points: 250,
    parTime: 15,
  },
  {
    id: "mid-cpp-int-to-longlong",
    language: "cpp" as Language,
    title: "int を long long に変換",
    description: "オーバーフロー対策のため、行頭の int 宣言をすべて long long に変換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "int a, b, c;",
      "int n, m;",
      "int ans = 0;",
      "int total = 0;",
    ].join("\n"),
    targetContent: [
      "long long a, b, c;",
      "long long n, m;",
      "long long ans = 0;",
      "long long total = 0;",
    ].join("\n"),
    hint: ":%s/^int/long long/g で行頭の int だけ置換",
    solution: ":%s/^int/long long/g<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-cpp-auto-loop",
    language: "cpp" as Language,
    title: "range-for の型を auto に変換",
    description: "range-for ループの int をすべて auto に変換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "for (int x : nums) {",
      "    sum += x;",
      "}",
      "for (int y : words) {",
      "    result.push_back(y);",
      "}",
      "for (int z : vals) {",
      "    total += z;",
      "}",
    ].join("\n"),
    targetContent: [
      "for (auto x : nums) {",
      "    sum += x;",
      "}",
      "for (auto y : words) {",
      "    result.push_back(y);",
      "}",
      "for (auto z : vals) {",
      "    total += z;",
      "}",
    ].join("\n"),
    hint: ":%s/for (int/for (auto/g で一括変換",
    solution: ":%s/for (int/for (auto/g<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-cpp-delete-include",
    language: "cpp" as Language,
    title: "不要なインクルードを削除",
    description: "<cstdio> と <cstring> のインクルード行を削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "#include <iostream>",
      "#include <cstdio>",
      "#include <vector>",
      "#include <cstring>",
      "#include <algorithm>",
    ].join("\n"),
    targetContent: [
      "#include <iostream>",
      "#include <vector>",
      "#include <algorithm>",
    ].join("\n"),
    hint: ":g/cstdio\\|cstring/d でどちらかにマッチする行を削除",
    solution: ":g/cstdio\\|cstring/d<CR>",
    points: 350,
    parTime: 20,
  },

  // ── Python ───────────────────────────────────────────────────────────────
  {
    id: "mid-py-delete-print",
    language: "python" as Language,
    title: "デバッグ用 print を削除",
    description: "デバッグ用の print 文をすべて削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "def binary_search(arr, target):",
      "    left, right = 0, len(arr) - 1",
      "    print(f'Searching for {target}')",
      "    while left <= right:",
      "        mid = (left + right) // 2",
      "        print(f'Checking index {mid}')",
      "        if arr[mid] == target:",
      "            return mid",
      "        elif arr[mid] < target:",
      "            left = mid + 1",
      "        else:",
      "            right = mid - 1",
      "    print('Not found')",
      "    return -1",
    ].join("\n"),
    targetContent: [
      "def binary_search(arr, target):",
      "    left, right = 0, len(arr) - 1",
      "    while left <= right:",
      "        mid = (left + right) // 2",
      "        if arr[mid] == target:",
      "            return mid",
      "        elif arr[mid] < target:",
      "            left = mid + 1",
      "        else:",
      "            right = mid - 1",
      "    return -1",
    ].join("\n"),
    hint: ":g/print/d でマッチした行をすべて削除",
    solution: ":g/print/d<CR>",
    points: 300,
    parTime: 20,
  },
  {
    id: "mid-py-rename-class",
    language: "python" as Language,
    title: "クラス名をリネーム",
    description: "'DataProcessor' をすべて 'Processor' にリネームせよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "class DataProcessor:",
      "    def __init__(self):",
      "        self.data = []",
      "",
      "    def process(self):",
      "        return self.data",
      "",
      "",
      "def create_processor():",
      "    return DataProcessor()",
      "",
      "",
      "processor = DataProcessor()",
    ].join("\n"),
    targetContent: [
      "class Processor:",
      "    def __init__(self):",
      "        self.data = []",
      "",
      "    def process(self):",
      "        return self.data",
      "",
      "",
      "def create_processor():",
      "    return Processor()",
      "",
      "",
      "processor = Processor()",
    ].join("\n"),
    hint: ":%s/DataProcessor/Processor/g で全置換（create_processor は大文字が違うので影響なし）",
    solution: ":%s/DataProcessor/Processor/g<CR>",
    points: 300,
    parTime: 20,
  },
  {
    id: "mid-py-add-default",
    language: "python" as Language,
    title: "デフォルト引数を追加",
    description: "timeout と retries 引数にデフォルト値を追加せよ（timeout=30, retries=3）",
    category: "editing",
    difficulty: "intermediate",
    initialContent: [
      "def connect(host, port, timeout):",
      "    return f'Connected to {host}:{port}'",
      "",
      "",
      "def request(url, method, retries):",
      "    return f'{method} {url}'",
    ].join("\n"),
    targetContent: [
      "def connect(host, port, timeout=30):",
      "    return f'Connected to {host}:{port}'",
      "",
      "",
      "def request(url, method, retries=3):",
      "    return f'{method} {url}'",
    ].join("\n"),
    hint: "/timeout で移動 → ea=30<Esc>、/retries で移動 → ea=3<Esc>",
    solution: "/timeout<CR> ea=30<Esc> /retries<CR> ea=3<Esc>",
    points: 400,
    parTime: 40,
  },
  {
    id: "mid-py-delete-assert",
    language: "python" as Language,
    title: "assert 文を削除",
    description: "デバッグ用の assert 文をすべて削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "def process(data, limit):",
      "    assert data is not None, 'data cannot be None'",
      "    assert limit > 0, 'limit must be positive'",
      "    result = [x for x in data if x < limit]",
      "    assert len(result) >= 0",
      "    return result",
    ].join("\n"),
    targetContent: [
      "def process(data, limit):",
      "    result = [x for x in data if x < limit]",
      "    return result",
    ].join("\n"),
    hint: ":g/assert/d でマッチした行をすべて削除",
    solution: ":g/assert/d<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-py-rename-var",
    language: "python" as Language,
    title: "変数名をリファクタリング",
    description: "'lst' をすべて 'arr' にリネームせよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "def merge_sort(lst):",
      "    if len(lst) <= 1:",
      "        return lst",
      "    mid = len(lst) // 2",
      "    left = merge_sort(lst[:mid])",
      "    right = merge_sort(lst[mid:])",
      "    return merge(left, right)",
    ].join("\n"),
    targetContent: [
      "def merge_sort(arr):",
      "    if len(arr) <= 1:",
      "        return arr",
      "    mid = len(arr) // 2",
      "    left = merge_sort(arr[:mid])",
      "    right = merge_sort(arr[mid:])",
      "    return merge(left, right)",
    ].join("\n"),
    hint: ":%s/lst/arr/g で全置換",
    solution: ":%s/lst/arr/g<CR>",
    points: 300,
    parTime: 20,
  },
  {
    id: "mid-py-rename-methods",
    language: "python" as Language,
    title: "メソッド名をリネーム",
    description: "'enqueue' を 'push' に、'dequeue' を 'pop' にリネームせよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "class Queue:",
      "    def __init__(self):",
      "        self.items = []",
      "",
      "    def enqueue(self, item):",
      "        self.items.append(item)",
      "",
      "    def dequeue(self):",
      "        return self.items.pop(0)",
      "",
      "",
      "q = Queue()",
      "q.enqueue(1)",
      "q.enqueue(2)",
      "q.dequeue()",
    ].join("\n"),
    targetContent: [
      "class Queue:",
      "    def __init__(self):",
      "        self.items = []",
      "",
      "    def push(self, item):",
      "        self.items.append(item)",
      "",
      "    def pop(self):",
      "        return self.items.pop(0)",
      "",
      "",
      "q = Queue()",
      "q.push(1)",
      "q.push(2)",
      "q.pop()",
    ].join("\n"),
    hint: ":%s/enqueue/push/g → :%s/dequeue/pop/g で2回置換",
    solution: ":%s/enqueue/push/g<CR>\n:%s/dequeue/pop/g<CR>",
    points: 350,
    parTime: 25,
  },

  // ── 応用テクニック ──────────────────────────────────────────────────────────
  {
    id: "mid-sort-imports",
    language: "python" as Language,
    title: "行をアルファベット順にソート (:sort)",
    description: "import 文をアルファベット順にソートせよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "import sys",
      "import os",
      "import json",
      "import re",
      "import math",
    ].join("\n"),
    targetContent: [
      "import json",
      "import math",
      "import os",
      "import re",
      "import sys",
    ].join("\n"),
    hint: ":sort でファイル全体をアルファベット順にソート",
    solution: ":sort<CR>",
    points: 250,
    parTime: 10,
  },
  {
    id: "mid-trim-whitespace",
    title: "末尾の空白を削除",
    description: "各行末に余分なスペースがある。すべて削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "hello   ",
      "world   ",
      "vim   ",
    ].join("\n"),
    targetContent: [
      "hello",
      "world",
      "vim",
    ].join("\n"),
    hint: ":%s/\\s\\+$// で末尾の空白（\\s）を1文字以上（\\+）まとめて削除",
    solution: ":%s/\\s\\+$//<CR>",
    points: 350,
    parTime: 20,
  },
  {
    id: "mid-move-line",
    language: "javascript" as Language,
    title: "行を移動 (:m)",
    description: "最終行の require 文を先頭に移動せよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: [
      "const app = express();",
      "const router = express.Router();",
      "const express = require('express');",
    ].join("\n"),
    targetContent: [
      "const express = require('express');",
      "const app = express();",
      "const router = express.Router();",
    ].join("\n"),
    hint: "G で最終行へ、:m 0 でファイル先頭（0行目の後）に移動",
    solution: "G :m 0<CR>",
    points: 350,
    parTime: 20,
  },
  {
    id: "mid-copy-range",
    language: "python" as Language,
    title: "行範囲をコピー (:t)",
    description: "1〜3行目の import 文を末尾にもコピーせよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: [
      "import os",
      "import sys",
      "import re",
      "",
      "# end of file",
    ].join("\n"),
    targetContent: [
      "import os",
      "import sys",
      "import re",
      "",
      "# end of file",
      "import os",
      "import sys",
      "import re",
    ].join("\n"),
    hint: ":1,3t$ で1〜3行目をファイル末尾（$）にコピー",
    solution: ":1,3t$<CR>",
    points: 350,
    parTime: 20,
  },
  {
    id: "mid-range-substitute",
    language: "python" as Language,
    title: "範囲指定で置換 (:2,4s)",
    description: "2〜4行目の 'TODO' だけを 'DONE' に置換せよ（1行目と5行目は変えない）",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "# TODO: design phase",
      "def task1():  # TODO",
      "def task2():  # TODO",
      "def task3():  # TODO",
      "# TODO: review phase",
    ].join("\n"),
    targetContent: [
      "# TODO: design phase",
      "def task1():  # DONE",
      "def task2():  # DONE",
      "def task3():  # DONE",
      "# TODO: review phase",
    ].join("\n"),
    hint: ":2,4s/TODO/DONE/g で2〜4行目のみ置換",
    solution: ":2,4s/TODO/DONE/g<CR>",
    points: 350,
    parTime: 20,
  },
  {
    id: "mid-range-delete",
    language: "python" as Language,
    title: "行範囲を削除 (:2,4d)",
    description: "2〜4行目のデバッグ設定をまとめて削除せよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: [
      "PORT = 3000",
      "DEBUG = True",
      "LOG_LEVEL = 'verbose'",
      "TRACE = True",
      "HOST = 'localhost'",
    ].join("\n"),
    targetContent: [
      "PORT = 3000",
      "HOST = 'localhost'",
    ].join("\n"),
    hint: ":2,4d で2〜4行目を一度に削除",
    solution: ":2,4d<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-word-boundary",
    language: "javascript" as Language,
    title: "単語境界で正確に置換 (\\<\\>)",
    description: "'count' のみを 'total' に置換せよ（'counting' は変えない）",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "let count = getCount();",
      "let counting = false;",
      "if (count > 0) {",
      "  count = count - 1;",
      "}",
      "return count;",
    ].join("\n"),
    targetContent: [
      "let total = getCount();",
      "let counting = false;",
      "if (total > 0) {",
      "  total = total - 1;",
      "}",
      "return total;",
    ].join("\n"),
    hint: ":%s/\\<count\\>/total/g で単語境界 \\< \\> を指定して完全一致のみ置換",
    solution: ":%s/\\<count\\>/total/g<CR>",
    points: 400,
    parTime: 25,
  },
  {
    id: "mid-add-prefix",
    title: "全行に接頭辞を追加 (:%s/^/)",
    description: "全行の行頭に '> ' を追加してクォートブロックにせよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "Hello there",
      "How are you",
      "I am fine",
      "Goodbye",
    ].join("\n"),
    targetContent: [
      "> Hello there",
      "> How are you",
      "> I am fine",
      "> Goodbye",
    ].join("\n"),
    hint: ":%s/^/> / で ^ (行頭) に '> ' を挿入",
    solution: ":%s/^/> /<CR>",
    points: 350,
    parTime: 15,
  },
  {
    id: "mid-add-suffix",
    language: "javascript" as Language,
    title: "全行末に文字を追加 (:%s/$/)",
    description: "配列要素の各行末にカンマを追加せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "  'apple'",
      "  'banana'",
      "  'cherry'",
      "  'date'",
    ].join("\n"),
    targetContent: [
      "  'apple',",
      "  'banana',",
      "  'cherry',",
      "  'date',",
    ].join("\n"),
    hint: ":%s/$/,/ で $ (行末) にカンマを追加",
    solution: ":%s/$/,/<CR>",
    points: 350,
    parTime: 15,
  },
  {
    id: "mid-join-multiple",
    title: "複数行を結合 (3J)",
    description: "3行に分かれたテキストを 1 行に結合せよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: [
      "Hello",
      "World",
      "Today",
    ].join("\n"),
    targetContent: "Hello World Today",
    hint: "gg で先頭へ、3J で3行まとめて結合（スペース区切り）",
    solution: "gg 3J",
    points: 250,
    parTime: 15,
  },

  // ── 新テクニック ──────────────────────────────────────────────────────────────
  {
    id: "mid-delete-blank-lines",
    language: "javascript" as Language,
    title: "空行を一括削除 (:g/^$/d)",
    description: "変数宣言の間にある空行をすべて削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "const host = \"localhost\";",
      "",
      "const port = 3000;",
      "",
      "const debug = true;",
      "",
      "const timeout = 5000;",
    ].join("\n"),
    targetContent: [
      "const host = \"localhost\";",
      "const port = 3000;",
      "const debug = true;",
      "const timeout = 5000;",
    ].join("\n"),
    hint: ":g/^$/ で空行にマッチし d で削除",
    solution: ":g/^$/d<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-gU-uppercase",
    language: "javascript" as Language,
    title: "定数名を大文字に変換 (gUe)",
    description: "小文字の定数名 max_retries, min_interval を大文字に変換せよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: [
      "const max_retries = 3;",
      "const min_interval = 100;",
    ].join("\n"),
    targetContent: [
      "const MAX_RETRIES = 3;",
      "const MIN_INTERVAL = 100;",
    ].join("\n"),
    hint: "w で定数名に移動し gUe で単語末まで大文字化。/min で2行目に移動して同様に",
    solution: "w gUe /min<CR> gUe",
    points: 350,
    parTime: 25,
  },
  {
    id: "mid-ci-quotes",
    language: "javascript" as Language,
    title: "文字列の中身を変更 (ci\")",
    description: "APIのURLを本番環境のものに書き換えよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: "const apiUrl = \"http://localhost:8080\";",
    targetContent: "const apiUrl = \"https://api.example.com\";",
    hint: "f\" でクォートに移動し ci\" で中身を丸ごと入れ替え",
    solution: "f\" ci\" https://api.example.com<Esc>",
    points: 350,
    parTime: 25,
  },
  {
    id: "mid-ci-parens",
    language: "javascript" as Language,
    title: "括弧内を丸ごと変更 (ci()",
    description: "setTimeout の引数をコールバックと遅延時間ごと書き換えよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: "setTimeout(handleTimeout, 1000);",
    targetContent: "setTimeout(handleRetry, 5000);",
    hint: "f( で括弧に移動し ci( で括弧内を丸ごと入れ替え",
    solution: "f( ci( handleRetry, 5000<Esc>",
    points: 400,
    parTime: 30,
  },
  {
    id: "mid-dW-remove",
    language: "javascript" as Language,
    title: "配列要素を削除 (dW)",
    description: "配列から 20 を削除せよ（後ろのカンマとスペースも含めて）",
    category: "editing",
    difficulty: "intermediate",
    initialContent: "const arr = [10, 20, 30, 40, 50];",
    targetContent: "const arr = [10, 30, 40, 50];",
    hint: "f2 で 20 に移動し dW で次の WORD の直前まで削除（20, と後続スペースを除去）",
    solution: "f2 dW",
    points: 350,
    parTime: 20,
  },
  {
    id: "mid-global-async-js",
    language: "javascript" as Language,
    title: ":g と :s の組み合わせ",
    description: "行頭が function で始まる関数をすべて async function にせよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "function fetchUser(id) {",
      "  return db.users.find(id);",
      "}",
      "",
      "function fetchPosts(userId) {",
      "  return db.posts.find(userId);",
      "}",
      "",
      "function deleteUser(id) {",
      "  return db.users.remove(id);",
      "}",
    ].join("\n"),
    targetContent: [
      "async function fetchUser(id) {",
      "  return db.users.find(id);",
      "}",
      "",
      "async function fetchPosts(userId) {",
      "  return db.posts.find(userId);",
      "}",
      "",
      "async function deleteUser(id) {",
      "  return db.users.remove(id);",
      "}",
    ].join("\n"),
    hint: ":g/^function/s/function/async function/ で行頭が function の行だけ対象に置換",
    solution: ":g/^function/s/function/async function/<CR>",
    points: 400,
    parTime: 25,
  },
  {
    id: "mid-js-strict-eq",
    language: "javascript" as Language,
    title: "== を === に変換（厳密等価）",
    description: "緩い等価演算子 == をすべて厳密等価 === に変換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "if (user == null) return;",
      "if (type == \"admin\") grant();",
      "if (status == 0) reset();",
      "if (value == undefined) skip();",
    ].join("\n"),
    targetContent: [
      "if (user === null) return;",
      "if (type === \"admin\") grant();",
      "if (status === 0) reset();",
      "if (value === undefined) skip();",
    ].join("\n"),
    hint: ":%s/ == / === /g でスペース付き == をスペース付き === に一括変換",
    solution: ":%s/ == / === /g<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-R-replace",
    language: "python" as Language,
    title: "上書きモード (R) で単語を置換",
    description: "ステータス文字列 \"loading\" を同じ文字数の \"success\" に上書きせよ",
    category: "mode",
    difficulty: "intermediate",
    initialContent: "status = \"loading\"",
    targetContent: "status = \"success\"",
    hint: "f\" で \" に移動、l で1文字進め、R で上書きモードに入り success と入力",
    solution: "f\" l R success<Esc>",
    points: 350,
    parTime: 25,
  },
  {
    id: "mid-yyp-dup",
    title: "行を複製 (yyp)",
    description: "1行目の設定行を複製して直下に貼り付けよ",
    category: "editing",
    difficulty: "intermediate",
    initialContent: [
      "host: primary.db.local",
      "host: secondary.db.local",
    ].join("\n"),
    targetContent: [
      "host: primary.db.local",
      "host: primary.db.local",
      "host: secondary.db.local",
    ].join("\n"),
    hint: "yyp で現在行をヤンクして直下に貼り付け",
    solution: "yyp",
    points: 250,
    parTime: 10,
  },
  {
    id: "mid-inline-comment-rm",
    language: "javascript" as Language,
    title: "インラインコメントを削除",
    description: "行末の // コメントをすべて削除せよ（セミコロンは残す）",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "const MAX = 100; // max limit",
      "const MIN = 0; // min limit",
      "const STEP = 5; // step size",
    ].join("\n"),
    targetContent: [
      "const MAX = 100;",
      "const MIN = 0;",
      "const STEP = 5;",
    ].join("\n"),
    hint: ":%s/ \\/\\/.*// でスペース+// 以降を全削除",
    solution: ":%s/ \\/\\/.*//g<CR>",
    points: 350,
    parTime: 20,
  },
  {
    id: "mid-cpp-vector-ll",
    language: "cpp" as Language,
    title: "vector<int> を vector<long long> に変換",
    description: "オーバーフロー対策として vector<int> をすべて vector<long long> に変換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "vector<int> dp(n + 1, 0);",
      "vector<int> dist(n, INF);",
      "vector<int> prefix(n + 1);",
      "vector<int> ans;",
    ].join("\n"),
    targetContent: [
      "vector<long long> dp(n + 1, 0);",
      "vector<long long> dist(n, INF);",
      "vector<long long> prefix(n + 1);",
      "vector<long long> ans;",
    ].join("\n"),
    hint: ":%s/vector<int>/vector<long long>/g で全置換",
    solution: ":%s/vector<int>/vector<long long>/g<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-cpp-endl-to-n",
    language: "cpp" as Language,
    title: "endl を \"\\n\" に変換（高速化）",
    description: "endl はバッファをフラッシュするため低速。すべて \"\\n\" に置換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "cout << \"Start\" << endl;",
      "cout << result << endl;",
      "cout << \"Done\" << endl;",
    ].join("\n"),
    targetContent: [
      "cout << \"Start\" << \"\\n\";",
      "cout << result << \"\\n\";",
      "cout << \"Done\" << \"\\n\";",
    ].join("\n"),
    hint: ":%s/<< endl/<< \"\\\\n\"/g で置換（\\\\n は vim replacement でリテラルの \\n）",
    solution: ":%s/<< endl/<< \"\\\\n\"/g<CR>",
    points: 400,
    parTime: 25,
  },
  {
    id: "mid-py-add-async",
    language: "python" as Language,
    title: "def を async def に変換",
    description: "行頭の def をすべて async def に変換せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "def get_user(user_id):",
      "    return await db.query(user_id)",
      "",
      "def get_posts(user_id):",
      "    return await db.posts(user_id)",
      "",
      "def update_user(user_id, data):",
      "    return await db.update(user_id, data)",
    ].join("\n"),
    targetContent: [
      "async def get_user(user_id):",
      "    return await db.query(user_id)",
      "",
      "async def get_posts(user_id):",
      "    return await db.posts(user_id)",
      "",
      "async def update_user(user_id, data):",
      "    return await db.update(user_id, data)",
    ].join("\n"),
    hint: ":%s/^def /async def / で行頭の def だけ置換",
    solution: ":%s/^def /async def /g<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-css-important",
    language: "css" as Language,
    title: "全プロパティに !important を追加",
    description: "リセット CSS の全プロパティに !important を付加せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      ".reset {",
      "  margin: 0;",
      "  padding: 0;",
      "  box-sizing: border-box;",
      "  outline: none;",
      "}",
    ].join("\n"),
    targetContent: [
      ".reset {",
      "  margin: 0 !important;",
      "  padding: 0 !important;",
      "  box-sizing: border-box !important;",
      "  outline: none !important;",
      "}",
    ].join("\n"),
    hint: ":%s/;/ !important;/g でセミコロンを !important; に置換",
    solution: ":%s/;/ !important;/g<CR>",
    points: 300,
    parTime: 15,
  },
  {
    id: "mid-py-del-todo",
    language: "python" as Language,
    title: "TODO コメント行を削除",
    description: "# TODO: で始まるコメント行をすべて削除せよ",
    category: "search",
    difficulty: "intermediate",
    initialContent: [
      "def setup():",
      "    # TODO: initialize database",
      "    pass",
      "",
      "def teardown():",
      "    # TODO: cleanup resources",
      "    pass",
      "",
      "def run():",
      "    return True",
    ].join("\n"),
    targetContent: [
      "def setup():",
      "    pass",
      "",
      "def teardown():",
      "    pass",
      "",
      "def run():",
      "    return True",
    ].join("\n"),
    hint: ":g/TODO/d で TODO を含む行を削除",
    solution: ":g/TODO/d<CR>",
    points: 300,
    parTime: 15,
  },
];

// ─── 上級 ────────────────────────────────────────────────────────────────────

const ADVANCED: Challenge[] = [
];

export const CHALLENGES: Challenge[] = [...BEGINNER, ...INTERMEDIATE, ...ADVANCED];

export const CATEGORIES: Record<Category, { label: string; icon: string }> = {
  movement: { label: "移動", icon: "🎯" },
  editing: { label: "編集", icon: "✏️" },
  mode: { label: "モード", icon: "🔄" },
  search: { label: "検索", icon: "🔍" },
};

export const DIFFICULTIES: Record<Difficulty, { label: string; icon: string; color: string }> = {
  beginner: { label: "初級", icon: "🌱", color: "green" },
  intermediate: { label: "中級", icon: "⚡", color: "yellow" },
  advanced: { label: "上級", icon: "🔥", color: "red" },
};
