export interface Course {
  id: string;
  title: string;
  description: string;
  icon: string;
  challengeIds: string[];
}

export const COURSES: Course[] = [
  {
    id: "course-movement-basics",
    title: "Vim 移動の基本",
    description: "hjkl から始まる移動コマンドを体系的に習得",
    icon: "🎯",
    challengeIds: [
      "hjkl-basic",
      "word-movement",
      "line-movement",
      "find-char",
      "goto-last-line",
      "goto-first-line",
      "goto-line-number",
      "first-nonblank",
      "match-paren",
      "count-motion",
      "till-char-delete",
      "prev-word-end",
    ],
  },
  {
    id: "course-editing-basics",
    title: "テキスト編集入門",
    description: "削除・変更・置換の基本コマンドをマスター",
    icon: "✏️",
    challengeIds: [
      "delete-char",
      "delete-word",
      "change-word",
      "delete-line",
      "change-to-eol",
      "delete-to-end",
      "delete-to-char",
      "replace-char",
      "join-lines",
      "change-line",
      "move-line",
    ],
  },
  {
    id: "course-yank-paste",
    title: "コピー＆ペースト術",
    description: "ヤンク・ペーストとテキストオブジェクトを使いこなす",
    icon: "📋",
    challengeIds: [
      "yank-paste",
      "change-inner-word",
      "delete-around-word",
      "change-inside-quotes",
      "delete-inside-quotes",
      "yank-multiple-lines",
      "yank-all-paste",
      "mid-yyp-dup",
    ],
  },
  {
    id: "course-modes",
    title: "モード切替マスター",
    description: "挿入・ビジュアル・置換モードを自由自在に操る",
    icon: "🔄",
    challengeIds: [
      "insert-mode",
      "insert-new-line",
      "insert-above",
      "insert-beginning",
      "append-word-end",
      "replace-mode",
      "visual-select-delete",
      "visual-line-delete",
      "visual-line-yank-paste",
    ],
  },
  {
    id: "course-search",
    title: "検索と置換",
    description: "/ 検索から :s 置換まで、テキスト探索を完全習得",
    icon: "🔍",
    challengeIds: [
      "search-basic",
      "search-under-cursor",
      "search-next",
      "search-backward",
      "search-case-insensitive",
      "search-replace",
      "line-substitute",
      "global-delete",
    ],
  },
  {
    id: "course-efficiency",
    title: "繰り返し＆効率化",
    description: ". リピートとカウント付きコマンドで編集を高速化",
    icon: "⚡",
    challengeIds: [
      "repeat-command",
      "count-delete-lines",
      "delete-multiple-words",
      "substitute-char",
      "toggle-case",
      "delete-to-eof",
      "delete-all-content",
      "mid-gU-uppercase",
      "mid-R-replace",
      "mid-dW-remove",
      "mid-ci-quotes",
    ],
  },
  {
    id: "course-advanced-text",
    title: "高度なテキスト操作",
    description: "範囲指定・行操作・テキストオブジェクトの応用技",
    icon: "🔧",
    challengeIds: [
      "mid-trim-whitespace",
      "mid-word-boundary",
      "mid-add-prefix",
      "mid-add-suffix",
      "mid-join-multiple",
      "mid-delete-blank-lines",
      "mid-ci-parens",
      "mid-copy-range",
      "mid-range-substitute",
      "mid-range-delete",
      "mid-sort-imports",
    ],
  },
  {
    id: "course-code-web",
    title: "実コード編集（JS/HTML/CSS）",
    description: "Web 系コードを Vim で素早く編集するテクニック",
    icon: "🌐",
    challengeIds: [
      "mid-rename-function",
      "mid-var-const",
      "mid-delete-logs",
      "mid-delete-comments",
      "mid-add-property",
      "mid-optional-chain",
      "mid-html-tags",
      "mid-global-async-js",
      "mid-js-strict-eq",
      "mid-inline-comment-rm",
      "mid-css-important",
    ],
  },
  {
    id: "course-code-python",
    title: "実コード編集（Python）",
    description: "Python コードの典型的な Vim 編集パターン",
    icon: "🐍",
    challengeIds: [
      "mid-py-delete-print",
      "mid-py-rename-class",
      "mid-py-add-default",
      "mid-py-delete-assert",
      "mid-py-rename-var",
      "mid-py-rename-methods",
      "mid-py-add-async",
      "mid-py-del-todo",
    ],
  },
  {
    id: "course-code-cpp",
    title: "実コード編集（C++）",
    description: "C++ コードに特化した編集テクニックを習得",
    icon: "⚙️",
    challengeIds: [
      "mid-cpp-delete-cerr",
      "mid-cpp-rename-func",
      "mid-cpp-null-to-nullptr",
      "mid-cpp-int-to-longlong",
      "mid-cpp-auto-loop",
      "mid-cpp-delete-include",
      "mid-cpp-vector-ll",
      "mid-cpp-endl-to-n",
    ],
  },
];
